# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
entries:
  - id: scotia_mit
    name: Scotia
    vendor: Scotia Contributors
    type: software
    required: true
    url: file:../LICENSE
    expand: true
