# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the Scotia QML view module.
---
# The QML is compiled into the plugin as a Qt resource.
qmlSearch: qrc
qmlFilename: scotia

# Default values for the options page.
scope: user
autostart: true
installShims: true
